{{- $fullName := include "sombra-chart.fullname" . -}}
{{- if .Values.transcend_ingress.enabled -}}
{{- $trancenIngressPort := .Values.transcend_service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "sombra-chart.fullname" . }}-transcend-ingress"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sombra-chart.labels" . | nindent 4 }}
  {{- with .Values.transcend_ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.transcend_ingress.className }}
  {{- if .Values.transcend_ingress.tls }}
  tls:
    {{- range .Values.transcend_ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.transcend_ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: "{{ $fullName }}-transcend-service"
                port:
                  number: {{ $trancenIngressPort }}
          {{- end }}
    {{- end }}
{{- end }}
---
{{- if .Values.customer_ingress.enabled -}}
{{- $fullCustomerServiceName := "sombra-customer-service" -}}
{{- $customerIngressPort := .Values.customer_service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "sombra-chart.fullname" . }}-customer-ingress"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sombra-chart.labels" . | nindent 4 }}
  {{- with .Values.customer_ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.customer_ingress.className }}
  {{- if .Values.customer_ingress.tls }}
  tls:
    {{- range .Values.customer_ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.customer_ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: "{{ $fullName }}-customer-service"
                port:
                  number: {{ $customerIngressPort }}
          {{- end }}
    {{- end }}
{{- end }}
