{{- $envs_as_secret_len := len .Values.envs_as_secret }}
{{- if gt  $envs_as_secret_len 0  -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: sombra-secrets
type: Opaque
data:
  {{- range $name, $value := .Values.envs_as_secret }}
  {{ $value.name }}: {{ $value.value | b64enc | quote  }}
  {{- end }}
---
{{- end }}
{{- define "imagePullSecret" }}
{{- with .Values.imageCredentials }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: transcend-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}