apiVersion: v2
name: sombra
description: A Helm chart to deploy Sombra and its dependent services in a Kubernetes cluster
type: application
version: 0.9.1
maintainers:
  - name: Transcend
    email: dev@transcend.io
dependencies:
  - name: llm-classifier
    condition: llm-classifier.enabled
    version: "0.2.2"
  - name: pathfinder
    condition: pathfinder.enabled
    version: "0.2.2"
  - name: sombra-job-scheduler
    condition: sombra-job-scheduler.enabled
    version: "0.1.1"
