{{- if and .Values.enabled .Values.tls.enabled  -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: llm-classifier-secrets
type: Opaque
data:
  llm-classifier.cert: {{ .Values.tls.cert | b64enc | quote  }}
  llm-classifier.key: {{ .Values.tls.key | b64enc | quote  }}
{{- end }}
