{{- $envs_as_secret_len := len .Values.envs_as_secret }}
{{- if and .Values.enabled . (gt  $envs_as_secret_len 0)  -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: pathfinder-secrets
type: Opaque
data:
  {{- range $name, $value := .Values.envs_as_secret }}
  {{ $value.name }}: {{ $value.value | b64enc | quote  }}
  {{- end }}
{{- end }}