{{- if and .Values.enabled .Values.proxyPolicy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-policy-config
  namespace: {{ .Values.namespace }}
data: |
  'pathfinder.yml': {{ .Values.proxyPolicy.policy }}
{{- end }}