name: Helm chart tests
on:
  pull_request:
    paths:
      - "charts/sombra/**/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.19.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install Helm unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Lint chart
        run: helm lint charts/sombra

      - name: Run Sombra chart tests
        shell: bash
        run: |
          cd charts/ ;
          helm unittest sombra ;
          helm unittest sombra/charts/job-scheduler ;
